
USE master
GO

CREATE DATABASE PHEP_JOIN
GO

USE PHEP_JOIN
GO

CREATE TABLE DONVI
(
   MADV  CHAR(2) NOT NULL,
   TENDV VARCHAR(50)
   
   CONSTRAINT PK_DONVI PRIMARY KEY ( MADV)
)
GO

CREATE TABLE NHANVIEN
(
   HOTEN VARCHAR(50),
   MADV  CHAR(2)
   
)
GO



-- THEM DU LIEU --

INSERT INTO DONVI VALUES ('1', 'Doi ngoai')
INSERT INTO DONVI VALUES ('2', 'Hanh chinh')
INSERT INTO DONVI VALUES ('3', 'Ke toan')
INSERT INTO DONVI VALUES ('4', 'Kinh doanh')
GO

INSERT INTO NHANVIEN VALUES ('Thanh', '1')
INSERT INTO NHANVIEN VALUES ('Hoa', '2')
INSERT INTO NHANVIEN VALUES ('Nam', '2')
INSERT INTO NHANVIEN VALUES ('Vinh', '1')
INSERT INTO NHANVIEN VALUES ('Hung', '5')
INSERT INTO NHANVIEN VALUES ('Phuong', NULL)
GO


SELECT * FROM NHANVIEN
GO

SELECT * FROM DONVI 
         INNER JOIN NHANVIEN ON DONVI.MADV = NHANVIEN.MADV
GO

SELECT * FROM DONVI
         LEFT OUTER JOIN NHANVIEN ON DONVI.MADV = NHANVIEN.MADV
GO

SELECT * FROM DONVI
         RIGHT OUTER JOIN NHANVIEN ON DONVI.MADV = NHANVIEN.MADV
GO

SELECT * FROM DONVI
         FULL OUTER JOIN NHANVIEN ON DONVI.MADV = NHANVIEN.MADV
GO


-- XÓA RÀNG BUỘC KHÓA NGOẠI --
 /* ALTER TABLE NHANVIEN DROP CONSTRAINT FK_DV_NHANVIEN
  GO */
